//
//  CocoaPods.swift
//  Thanks
//
//  Created by mba0 on 2018/12/31.
//

import Foundation

let cocoapodAckFileFooterMark = "Generated by CocoaPods - https://cocoapods.org"

public func cocoaPodsLicenses(from ackFile: FileContent, in filename: String) -> [License] {
    return ackFile.components(separatedBy: .newlines)
        .reduce([String]()) { rs, line in // remove header and footer
            var rs = rs

            if rs.count == 0, line.hasPrefix("## ") {
                rs.append(line)
            } else if let last = rs.last, !last.contains(cocoapodAckFileFooterMark) {
                rs.append(line)
            }

            return rs
        }.dropLast() // remove lastMark
        .reduce([(name: String, contents: [String])]()) { rs, line in // split each projects

            var rs = rs

            if line.hasPrefix("## ") {
                // remove markdown header
                rs.append((name: line.replacingOccurrences(of: "## ", with: ""), contents: []))
            } else {
                let index = rs.index(before: rs.endIndex)
                rs[index].contents.append(line)
            }

            return rs
        }.map { elem in
            License(projectName: elem.name, body: elem.contents.joined(separator: "\n"), provider: .cocoaPods(filename: filename))
        }
}
