platform :ios, '9.3'

target 'TestProject' do
	use_frameworks!

	pod 'GoogleToolboxForMac/NSString+HTML'
	pod 'GoogleToolboxForMac/NSDictionary+URLArguments'
	pod 'Punycode-Cocoa',  '~> 1.3'
	pod 'Underscore.m', '~> 0.3.0'
	pod 'Firebase/Core'
	pod 'Firebase/Auth'
	pod 'Firebase/Database'
	pod 'Firebase/RemoteConfig'
	pod 'Firebase/Messaging'
	pod 'Firebase/AdMob'
	pod 'Fabric'
	pod 'Crashlytics'
	pod 'TwitterKit'
	pod 'OAuthCore', '~> 0.0.1'
	pod 'Reachability'
	pod 'FlickrKit',   '~> 1.0.7'
	pod 'TKRSegueOptions'
	pod 'twitter-text',  '~> 3.0.0'
	pod 'LXReorderableCollectionViewFlowLayout'
	pod 'PSPDFTextView'
	pod 'Ono',  '~> 1.2.0'
	pod 'HexColors', '~> 4.0.0'
	pod 'GBDeviceInfo'
	pod 'SGNavigationProgress',  '~> 1.2'
	pod 'MMMarkdown'
	pod 'Block-KVO'
	pod 'OHHTTPStubs', '~> 6.1.0'
	pod 'OHHTTPStubs/Swift'

    target 'TestProjectTests' do
        pod 'OCMock'
    end

end

# vim: ft=ruby

